---
title: "Data Analysis - Project Proposal"
author: "Mohamed Diakite Pineda, Yu Liu, Diego Carreno, STAT 420, Summer 2020"
date: "7/19/2020"
output:
  html_document: 
    theme: readable
    toc: yes
  pdf_document: default
urlcolor: cyan
---

***

## Student names

- Mohamed Diakite Pineda, *md21@*
- Yu Liu, *yul10@*
- Diego Carreno, *diegoac3@*

## Project Title

Building a predictive model for startup invesments and valuation

## Description of the data file

Pending.

## Background information of the data set

The data set comes from Kaggle (see [source](https://www.kaggle.com/justinas/startup-investments?select=funding_rounds.csv)), and it contains diverse data from the startup environment in 2013. It includes, but is not limited to:

- Organizations
- Founders information
- Rounds and funding dates
- Acquisitions
- Valuation

## Purpose statement

We are interested in predicting startup success and valuation given a combination of factors, such as number of founders, rounds of funding, number of aquisitions, founders background, and location among others. We want to explore and see if there are specific predictor variables from which we can build a model that can explain startup success and/or valuation reasonably well.

## Loading the data into `R`

Pending.